<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-13T11:51:27 IST" name="testing" finished-at="2023-09-13T11:52:10 IST" duration-ms="42946">
    <groups>
    </groups>
    <test started-at="2023-09-13T11:51:27 IST" name="both" finished-at="2023-09-13T11:52:10 IST" duration-ms="42946">
      <class name="firstmaven.ProductAddingToCart">
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:firstmaven.ProductAddingToCart@1750fbeb]" started-at="2023-09-13T11:51:27 IST" name="lanchApplication" finished-at="2023-09-13T11:51:40 IST" duration-ms="12764" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="addingProductToValidationtest()[pri:0, instance:firstmaven.ProductAddingToCart@1750fbeb]" started-at="2023-09-13T11:51:40 IST" name="addingProductToValidationtest" finished-at="2023-09-13T11:51:44 IST" duration-ms="4296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addingProductToValidationtest -->
        <test-method is-config="true" signature="driverClose()[pri:0, instance:firstmaven.ProductAddingToCart@1750fbeb]" started-at="2023-09-13T11:51:44 IST" name="driverClose" finished-at="2023-09-13T11:51:44 IST" duration-ms="498" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverClose -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:firstmaven.ProductAddingToCart@1750fbeb]" started-at="2023-09-13T11:51:44 IST" name="lanchApplication" finished-at="2023-09-13T11:51:50 IST" duration-ms="5544" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="addingProducttest()[pri:0, instance:firstmaven.ProductAddingToCart@1750fbeb]" started-at="2023-09-13T11:51:50 IST" name="addingProducttest" finished-at="2023-09-13T11:51:56 IST" duration-ms="5642" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addingProducttest -->
        <test-method is-config="true" signature="driverClose()[pri:0, instance:firstmaven.ProductAddingToCart@1750fbeb]" started-at="2023-09-13T11:51:56 IST" name="driverClose" finished-at="2023-09-13T11:51:56 IST" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverClose -->
      </class> <!-- firstmaven.ProductAddingToCart -->
      <class name="firstmaven.ErrorValidation">
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:firstmaven.ErrorValidation@723ca036]" started-at="2023-09-13T11:51:56 IST" name="lanchApplication" finished-at="2023-09-13T11:52:02 IST" duration-ms="5780" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method retried="true" signature="inCorrectLoginErrorValidationtest()[pri:0, instance:firstmaven.ErrorValidation@723ca036]" started-at="2023-09-13T11:52:02 IST" name="inCorrectLoginErrorValidationtest" finished-at="2023-09-13T11:52:02 IST" duration-ms="825" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at firstmaven.ErrorValidation.inCorrectLoginErrorValidationtest(ErrorValidation.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inCorrectLoginErrorValidationtest -->
        <test-method is-config="true" signature="driverClose()[pri:0, instance:firstmaven.ErrorValidation@723ca036]" started-at="2023-09-13T11:52:02 IST" name="driverClose" finished-at="2023-09-13T11:52:03 IST" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverClose -->
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:firstmaven.ErrorValidation@723ca036]" started-at="2023-09-13T11:52:03 IST" name="lanchApplication" finished-at="2023-09-13T11:52:09 IST" duration-ms="5949" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="inCorrectLoginErrorValidationtest()[pri:0, instance:firstmaven.ErrorValidation@723ca036]" started-at="2023-09-13T11:52:09 IST" name="inCorrectLoginErrorValidationtest" finished-at="2023-09-13T11:52:10 IST" duration-ms="907" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at firstmaven.ErrorValidation.inCorrectLoginErrorValidationtest(ErrorValidation.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inCorrectLoginErrorValidationtest -->
        <test-method is-config="true" signature="driverClose()[pri:0, instance:firstmaven.ErrorValidation@723ca036]" started-at="2023-09-13T11:52:10 IST" name="driverClose" finished-at="2023-09-13T11:52:10 IST" duration-ms="198" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverClose -->
      </class> <!-- firstmaven.ErrorValidation -->
    </test> <!-- both -->
  </suite> <!-- testing -->
</testng-results>
